#!/bin/bash -e

serverIp=$(hostname -I)
clientIp=$(echo $serverIp | cut -d '.' -f 1-3).255 # Send to all

gst-launch-1.0 -v alsasrc device=plughw:Device ! mulawenc ! rtppcmupay ! udpsink host=$clientIp port=5001 &

 raspivid -t 0 -w 800 -h 600 -fps 18 -vf -hf -b 2000000 -o - | gst-launch-1.0 -v fdsrc ! h264parse ! rtph264pay config-interval=1 pt=96 ! gdppay ! tcpserversink host=$serverIp port=5000

kill $!
